openapi: '3.0.3'
info:
  title: Music Social Media API
  description: Rest API for a social media platform with ML-based Content/Collaborative/Hybrid User Specific Recommendations
  version: '1.0'

servers:
  - url: https://mt241063-10974.node.ustp.cloud
    description: Deployment
  - url: http://localhost:3000/
    description: Local Testing
paths:
  /auth/register:
    post:
      summary: "Register a new User"
      tags: [ Auth ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegistration"

      responses:
        "201":
          description: "User was created successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthSuccessfulResponse"
        "400":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

        "409":
          description: "Invalid input"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              examples:
                UsernameTaken:
                  value:
                    message: "Username already taken"
                    code: "USERNAME_TAKEN"
                EMailTaken:
                  value:
                    message: "E-Mail is already used for another account"
                    code: "EMAIL_TAKEN"

  /auth/login:
    post:
      summary: "Login an existing user"
      tags: [ Auth ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLogin"
      responses:
        "200":
          description: "User logged in successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthSuccessfulResponse"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

        "401":
          description: "Wrong Credentials"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              example:
                message: "Wrong Username or Password"
                code: "WRONG_CREDENTIALS"

  /users/self/content_preferences:
    patch:
      summary: "Change content preferences from default values"
      tags: [ Users ]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserContentPreferences"
      responses:
        "200":
          description: "Preferences updated successfully"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

  /users/self/ui_settings:
    patch:
      summary: "Change UI Settings from default values"
      tags: [ Users ]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserUISettings"
      responses:
        "200":
          description: "Preferences updated successfully"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

  /users/self/profile:
    patch:
      summary: "Update the Users Profile (Picture and Description)"
      tags: [ Users ]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/UserProfileUpdate"
      responses:
        "200":
          description: "Preferences updated successfully"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              example:
                message: "The Picture exceeds the maximum file size of 5MB"
                code: "IMAGE_TOO_LARGE"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

  /users/{username}/loadprofile:
    get:
      summary: "Load the Profile Page of a user"
      tags: [ Pages ]
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Valid Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProfilePageResponse"

        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              example:
                message: "The Picture exceeds the maximum file size of 5MB"
                code: "IMAGE_TOO_LARGE"

  /users/self/history:
    get:
      summary: "Load the previously seen posts for the logged in user"
      tags: [ Pages ]
      security:
        - BearerAuth: []
      responses:
        "200":
          description: "Valid Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HistoryResponse"

        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              example:
                message: "The Picture exceeds the maximum file size of 5MB"
                code: "IMAGE_TOO_LARGE"

        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"

  /users/recommendations:
    get:
      summary: "Gets personalized recommendations for a specific user"
      security:
        - BearerAuth: []
      tags: [ Recommendations ]
      responses:
        "200":
          description: "Valid Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecommendationsResponse"

        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              example:
                  message: "Your Session has expired. Please log in again."
                  code: "TOKEN_EXPIRED"

  /guest/recommendations:
    get:
      summary: "Gets a generalised recommendation for not logged in users"
      tags: [ Recommendations ]
      responses:
        "200":
          description: "Valid Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecommendationsResponse"

  /users/follow/{username}:
    post:
      summary: "Triggered when a user wants to follow another user"
      tags: [ UserActions ]
      security:
        - BearerAuth: []
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Followed successfully"

        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              example:
                message: "You need to be logged in in order to follow another user."
                code: "NOT_LOGGED_IN"

  /users/unfollow/{username}:
    post:
      summary: "Triggered when a user wants to unfollow another user"
      tags: [ UserActions ]
      security:
        - BearerAuth: [ ]
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Unfollowed successfully"

        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              example:
                message: "YouÂ´re not following this user."
                code: "NOT_FOLLOWED"

        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              example:
                message: "You need to be logged in in order to unfollow another user."
                code: "NOT_LOGGED_IN"


  /interactions/posts/{post_id}/like:
    post:
      summary: "Like a specific post"
      tags: [ Interactions ]
      security:
        - BearerAuth: []
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: string

      responses:
        "200":
          description: "Liked successfully"

        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              example:
                message: "You need to be logged in in order to follow another user."
                code: "NOT_LOGGED_IN"

  /interactions/posts/{post_id}/view:
    post:
      summary: "Sent to API in order to document watchtime"
      tags: [ Interactions ]
      security:
        - BearerAuth: [ ]
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                watch_time_seconds:
                  type: integer
                  description: "Seconds the user has watched the post"
                  example: 36
                completed:
                  type: boolean
                  description: "The post was viewed for >= 90% of the post-duration"
      responses:
        "200":
          description: "Watchtime stored successfully"

        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              example:
                message: "You need to be logged in in order to store watchtime"
                code: "NOT_LOGGED_IN"

  /interactions/posts/{post_id}/comment:
    post:
      summary: "Comment on a post by logged in user"
      tags: [ Interactions ]
      security:
        - BearAuth: []
      parameters:
        - name: post_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                comment:
                  type: string
                  description: "Comment by the user"
                  example: "Great Song!"

      responses:
        "200":
          description: "Watchtime stored successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CommentResponse"

        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              example:
                message: "Comment field is empty"
                code: "MISSING_FIELDS"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              example:
                message: "You need to be logged in in order to store watchtime"
                code: "NOT_LOGGED_IN"

  
  
  
  /post:
    post:
      summary: "Upload a post"
      tags: [ Posts ]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/PostUpload"
      responses:
        "200":
          description: "Post uploaded successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostResponse"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              examples:
                ImageTooLarge:
                  summary: Picture too large
                  value:
                    message: "The picture exceeds the maximum file size of 5MB"
                    code: "IMAGE_TOO_LARGE"
                AudioTooLarge:
                  summary: Audio too large
                  value:
                    message: "The audio file exceeds the maximum file size of 5MB"
                    code: "AUDIO_TOO_LARGE"
                MissingFields:
                  summary: Missing fields
                  value:
                    message: "Missing required fields: post_title, post_audio"
                    code: "MISSING_FIELDS"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              example:
                message: "Session expired please log in"
                code: "TOKEN_EXPIRED"


                
  /post/{post_id}:
    get:
      summary: "Get the Post for the user to view"
      tags: [ Posts ]
      parameters:
        - name: post_id
          in: path
          required: true
          schema: 
            type: string
      responses:
        "200":
          description: "Post fetched successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostResponse"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              examples:

                InvalidInput:
                  summary: Invalid input
                  value:
                    message: "This is not a valid input."
                    code: "INVALID_INPUT"
    patch:
      summary: "Change values of a already existing post"
      tags: [ Posts ]
      security:
        - BearerAuth: [ ]
      parameters:
        - name: post_id
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/PostUpdate"
      responses:
        "200":
          description: "Post updated successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostResponse"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              examples:
                ImageTooLarge:
                  summary: Picture too large
                  value:
                    message: "The picture exceeds the maximum file size of 5MB"
                    code: "IMAGE_TOO_LARGE"
                InvalidInput:
                  summary: Invalid input
                  value:
                    message: "This is not a valid input."
                    code: "INVALID_INPUT"
        "401":
          description: "Unauthorized"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              example:
                message: "Session expired please log in"
                code: "TOKEN_EXPIRED"

  
  /post/{post_id}/comments:
    get:
      summary: "Loads all the comments for a specific post"
      tags: [ Posts ]
      parameters:
        - name: post_id
          in: path
          schema: 
            type: string
      responses:
        "200":
          description: "Comments fetched successfully"
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/CommentResponse"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorMessage"
              examples:
                ImageTooLarge:
                  summary: Picture too large
                  value:
                    message: "The picture exceeds the maximum file size of 5MB"
                    code: "IMAGE_TOO_LARGE"
                InvalidInput:
                  summary: Invalid input
                  value:
                    message: "This is not a valid input."
                    code: "INVALID_INPUT"

components:
  schemas:
    AccessToken:
      type: string
      example: "56071515540"
      description: "JWT Access Token"


    UserRegistration:
      allOf:
        - $ref: "#/components/schemas/UserBase"
        - type: object
          properties:
            password:
              type: string
              example: "verysecretpassword"

    UserBase:
      type: object
      minProperties: 1
      properties:
        username:
          type: string
          example: "best_username_is_mike"
        email:
            type: string
            example: "email@themail.at"

    UserLogin:
      type: object
      minProperties: 1
      properties:
        username:
          type: string
          example: "best_username_is_mike"
        password:
          type: string
          example: "verysecretpassword"


    UserPublic:
      allOf:
        - $ref: "#/components/schemas/UserBase"
        - type: object
          properties:
            user_id:
                type: integer
                example: 1234

    UserContentPreferences:
      type: object
      minProperties: 1
      properties:
        content_language:
          type: string
          example: "en"
        recommendation_algorithm:
          type: string
          enum: ["content_based", "collaborative", "hybrid"]
          description: "Select recommendation strategy"
        preferred_genres:
          type: array
          example: ["Rock","Reggae"]
          items:
            type: string
        autoplay:
          type: boolean

    UserUISettings:
      type: object
      minProperties: 1
      properties:
        ui_language:
          type: string
          example: "en"
        theme:
          type: string
          enum: ["dark","light", "custom"]

    UserProfileUpdate:
      type: object
      minProperties: 1
      properties:
        profile_picture:
          type: string
          format: binary
          description: "Profile Picture"
        profile_description:
          type: string
          example: "This is my profile :3"


    PostBase:
      type: object
      required: [ post_title, post_description ]
      properties:
        post_title:
          type: string
          description: "Title for the Post"
          example: "Great Post Title"

        post_description:
          type: string
          description: "Description and additional infos to the post"

    PostUpdateableParameters:
      type: object
      properties:
        post_image:
          type: string
          format: binary
          description: "Image for the Post"

        post_tags:
          type: array
          items:
            type: string
          description: "Tags to be associated with the post"
          example: [ "chill", "dnb", "great culture" ]

        post_audio_genre:
          type: array
          description: "Genre of the post audio. Separate from post_tags"
          items:
            type: string
          example: [ "Reggae","Progressive Rock" ]

    PostUpload:
        allOf:
          - $ref: "#/components/schemas/PostBase"
          - $ref: "#/components/schemas/PostUpdateableParameters"
          - type: object
            required: [post_audio, post_image, post_audio_genre]
            properties:

              post_audio:
                type: string
                format: binary
                description: "Audio for the Post"

    PostUpdate:
      minProperties: 1
      allOf:
        - type: object
          properties:
           post_title:
              type: string
              description: "Title for the Post"
              example: "Great Post Title"

           post_description:
              type: string
              description: "Description and additional infos to the post"
        - $ref: "#/components/schemas/PostUpdateableParameters"


    PostResponse:
      allOf:
        - $ref: "#/components/schemas/PostBase"
        - type: object
          properties:
            post_id:
              type: integer
              description: "ID of a specific post"
              example: 276
            post_audio_url:
              type: string
              format: url
              description: "Path to the Audio file for the post"
              example: "localhost:3000/post_id/audiofilename.mp3"
            post_image_url:
              type: string
              format: url
              description: "Path to the Image file for the post"
              example: "localhost:3000/post_id/imagefilename.png"
            post_likes_count:
              type: integer
              description: "Number of likes on that post"
              example: "24"
            post_comments_count:
              type: integer
              description: "Number of comments on that post"
              example: "3"

    PostPreview:
      type: object
      properties:
        post_id:
          type: integer
          description: "ID of the Post"
          example: "1234"
        post_title:
          type: string
          description: "Title of the Post"
          example: "Greatest Post Ever!"
        preview_image_path:
          type: string
          description: "Path of the preview image"
          example: "localhost:3000/post_id/previewimagefilename.png"


    ProfileInformation:
      type: object
      properties:
        username:
          type: string
          description: "Username of a Profile owner"
          example: "Mike"
        description:
          type: string
          description: "Description of a profile"
          example: "Welcome to my profile"

    ProfilePageResponse:
      allOf:
        - $ref: "#/components/schemas/ProfileInformation"
        - type: object
          properties:
            posts:
              type: array
              items: 
                $ref: "#/components/schemas/PostPreview"

    CommentResponse:
      type: object
      properties:
        username:
          type: string
          description: "Username of a Profile owner"
          example: "Mike"
        comment:
          type: string
          description: "Comment made by the user"
          example: "Great post!"
        date_time:
          type: string
          format: date-time
          description: "Time when the comment was posted"
          example: "2026-01-23T18:15:00Z"

    HistoryResponse:
      type: array
      items:
        allOf:
          - $ref: "#/components/schemas/PostPreview"
          - type: object
            properties:
              viewed_at:
                type: string
                format: date-time
                description: "Time when the post was viewed"
                example: "2026-01-23T16:36:00Z"

    RecommendationsResponse:
      type: array
      items:
        $ref: "#/components/schemas/PostPreview"

    AuthSuccessfulResponse:
      type: object
      properties:
        token:
          $ref: "#/components/schemas/AccessToken"
        user:
          $ref: "#/components/schemas/UserPublic"

    ErrorMessage:
      type: object
      properties:
        message:
          type: string
          example: "Wrong credentials"
        code:
          type: string
          example: "INVALID_CREDENTIALS"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


